// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPvgDBOTnu0ledv1Vgdm_6EV-GBvgyGaw',
    appId: '1:522024438545:web:36e19d172c91652e68dab0',
    messagingSenderId: '522024438545',
    projectId: 'stall-manager',
    authDomain: 'stall-manager.firebaseapp.com',
    storageBucket: 'stall-manager.appspot.com',
    measurementId: 'G-1NNGQPWW5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-juDlh12wgpHQ_VRhMgmLVsTI-jJ27ho',
    appId: '1:522024438545:android:d14e0b7846bb693f68dab0',
    messagingSenderId: '522024438545',
    projectId: 'stall-manager',
    storageBucket: 'stall-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw53Pz-ZU-GeoMrUyhdFS0WRnejt4UGZo',
    appId: '1:522024438545:ios:1111899a841485b268dab0',
    messagingSenderId: '522024438545',
    projectId: 'stall-manager',
    storageBucket: 'stall-manager.appspot.com',
    iosClientId: '522024438545-mhf5o40dbdbstt8ceie6k1rvuc10r8hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.stallManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw53Pz-ZU-GeoMrUyhdFS0WRnejt4UGZo',
    appId: '1:522024438545:ios:1111899a841485b268dab0',
    messagingSenderId: '522024438545',
    projectId: 'stall-manager',
    storageBucket: 'stall-manager.appspot.com',
    iosClientId: '522024438545-mhf5o40dbdbstt8ceie6k1rvuc10r8hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.stallManager',
  );
}
